#!/bin/sh

# Loop through all attached batteries and format the info
for battery in /sys/class/power_supply/BAT?*; do
	# If non-first battery, print a space separator.
	[ -n "${capacity+x}" ] && printf " "
	# Sets up the status and capacity
	case "$(cat "$battery/status" 2>&1)" in
		"Full") status="Full" ;;
		"Discharging") status="Discharging" ;;
		"Charging") status="Charging" ;;
		"Not charging") status="Not Charging" ;;
		"Unknown") status="Unknown" ;;
		*) exit 1 ;;
	esac
	capacity="$(cat "$battery/capacity" 2>&1)"

	if [[ $capacity -ge 90 ]]; then
		icon=""
	elif [[ $capacity -ge 75 && $capacity -lt 90 ]]; then
		icon=""
	elif [[ $capacity -ge 50 && $capacity -lt 75 ]]; then
		icon=""
	elif [[ $capacity -ge 25 && $capacity -lt 50 ]]; then
		icon=""
	elif [[ $capacity -lt 25 ]]; then
		icon=""
	fi
	# Will make a warn variable if discharging and low
	[ "$status" = "Discharging" ] && [ "$capacity" -le 25 ] && warn="❗"
	# Prints the info
	printf "%s%s%d%%" "$icon " "$warn" "$capacity"; unset warn
done && printf "\\n"
